# Generated by Django 6.1 on 2026-08-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tone.user',),
        ),
    ]
